### ISSUE TITLE
Header location

### ISSUE THREAD

**Issue by KhaledSMQ** [tusdotnet/tusdotnet#40] opened 2017-12-13 05:36 UTC
When you are in local host or standalone application on IIS Header location is correct using UrlPath configuration but the problem when you are in sub application the Header location might be different than the UrlPath i solve this problem by modify the default configuration  and add my custom header location response.
https://github.com/tusdotnet/tusdotnet/blob/master/Source/tusdotnet/ProtocolHandlers/PostHandler.cs#L122
```
response.SetHeader(HeaderConstants.Location, $"context.Configuration.LocationPath.TrimEnd('/')}/{fileId}");
```
i am not sure if there is better solution such as get the Request path and add it as header or make it customizable  by adding path of header response in configuration.

**Comment by smatsson** [comment] 2017-12-13 14:15
If you are on a hosting plan were your site is located in a subdirectory (e.g. www.example.org/mywebsite/) then you will have to specify the subpath in `UrlPath` when you configure tusdotnet. In that case the line you show above will work. See comment above property: https://github.com/tusdotnet/tusdotnet/blob/master/Source/tusdotnet/Models/DefaultTusConfiguration.cs#L19

Having different values for `UrlPath` and the location header will result in a bunch of unexpected bugs as these must match so that tusdotnet can operate as it should.

**Comment by KhaledSMQ** [comment] 2017-12-13 15:13
exactly, but when i specify the UrlPath with sub-host it end up with 404 look like the route registered wrong for the initial post from Tus protocol.

**Comment by smatsson** [comment] 2017-12-14 10:51
What request ends up with a 404 response? Could you please provide me with a step by step guide for the requestes being made?

**Comment by KhaledSMQ** [comment] 2017-12-14 20:49
Okay here is the scenario.
I have Front-end app and the back-end hosted as sub application in example i used the samples in the  project

Upload file -> post initial return response 201 created with worng header location 
 
![inital](https://user-images.githubusercontent.com/8835798/34013298-4dde50ec-e130-11e7-8e4b-b53ead4a7440.png)

![first-chunk](https://user-images.githubusercontent.com/8835798/34013299-4e0fad5e-e130-11e7-9fc6-b66161afe97f.png)

update url path as following
UrlPath = "/sub/files", results response 404

![updated configuration](https://user-images.githubusercontent.com/8835798/34013481-1ee5ce86-e131-11e7-8d19-0e1e7c4d4c77.png)

**Comment by smatsson** [comment] 2017-12-15 02:19
Thanks for the screenshots! It made it much easier to understand the issue. I will look into it. Are you running on ASP.NET Core or classic ASP.NET?

**Comment by KhaledSMQ** [comment] 2017-12-15 10:17
ASP.NET Core 2.0

**Comment by smatsson** [comment] 2017-12-15 10:39
Cool. Then I know what the issue is. ASP.NET Core changes how URI handling works in so that the "path base" is no longer included in local path (as it was in classic ASP.NET). I have a fix for it and will publish a new nuget package sometime early next week. The fix is in the master branch if you want to compile it yourself before that. :)

**Comment by KhaledSMQ** [comment] 2017-12-15 11:32
Thank you so much for the fix.

**Comment by smatsson** [comment] 2018-01-03 10:54
The release is now on Nuget. It was delayed due to Christmas and New Year's eve. :) 

Please let me know if you have any further issues.

**Closed by smatsson** 2018-01-03 10:54 UTC
Labels: bug

**Comment by TravisYeah** [comment] 2019-04-17 18:58
This issue may not be completely resolved. I still have issues on IIS that I do not have locally even when the subfolder name is included in the endpoint. I created a fresh net core 2.1 mvc app and added tusdotnet and I get a 404 error for the patch request while it states the following uri format: https://HOST_NAME/SUB_FOLDER/URL_PATH/FILE_ID. Any ideas?

**Comment by smatsson** [comment] 2019-04-23 08:00
@TravisYeah Hard to tell without knowing your configuration. Did you set the UrlPath in your DefaultTusConfiguration to "/subfolder/urlpath"?

**Comment by smatsson** [comment] 2019-04-24 05:05
@TravisYeah Just tested this on IIS10 and it worked just fine. Added a application as a sub entry to the default website and deployed the tusdotnet test site for ASP.NET Core 2.1 to it.

![iis config](https://user-images.githubusercontent.com/4600361/56633613-29c1be00-665f-11e9-89f4-0661856076cf.png)

Navigated to url

![url](https://user-images.githubusercontent.com/4600361/56633547-dfd8d800-665e-11e9-90a1-7e4d6130aa62.png)


Upload starts as expected

![Upload progress](https://user-images.githubusercontent.com/4600361/56633625-33e3bc80-665f-11e9-80ea-34268ce5e36a.png)

And location header includes the subfolder

![header](https://user-images.githubusercontent.com/4600361/56633640-3f36e800-665f-11e9-8a1d-3bb15be19684.png)

Not sure how to help you unless I know more about your setup.

**Comment by TravisYeah** [comment] 2019-04-24 14:46
@smatsson thanks for investigating. I will try to circle back to this soon.

**Comment by TravisYeah** [comment] 2020-06-26 16:37
@smatsson just following up on this after the long wait. I had been testing this on my staging server which I forget to also configure as described in the [wiki](https://github.com/tusdotnet/tusdotnet/wiki/Configure-IIS).

**Comment by smatsson** [comment] 2020-06-26 17:26
@TravisYeah Glad to hear it was solved. 👍
