### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by EverEcheverri** [tusdotnet/tusdotnet#87] opened 2020-03-13 15:00 UTC
Hi guys, after updating to version 2.2.2 the memory does not exceed 700 MB, that's good, the problem is that when I finish uploading my files, it never frees up the memory it uses, once reaches 700 MB there it remains, the only way to free memory is to restart the service.

![memory_1](https://user-images.githubusercontent.com/10034383/76632437-3a964f00-6511-11ea-9fac-40aa8612bc4e.png)

![memory_2](https://user-images.githubusercontent.com/10034383/76632482-4c77f200-6511-11ea-9c7f-f42cc4ff592b.png)

**Comment by smatsson** [comment] 2020-03-20 13:34
Hi,

Thanks for reporting and kudos on the descriptive issue.

This is a known issue without an easy fix. It all boils down to how .NET places large objects (> 80 KB) place in the [Large Object Heap (LOH)](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap). Objects in the LOH are not garbage collected the same way as regular objects (not at all in my experience).

The earlier versions of tusdotnet used a single 50 KB buffer per request for reading and writing files. Data was read and then immediately written to disk. As pointed out in PR #57 this caused performance issues with CPU and disk if you had many slow connections connected at the same time. The PR added support for setting the write buffer size but the implementation contained a hard to find bug which caused memory leaks in some cases even for the default buffer size (as described in your earlier issue). To circumvent this we put all buffers into an `ArrayPool<T>` to reuse the buffers (which are arrays) between requests. The downside to this is, as you pointed out, that memory is not returned as the buffers are cached and will be used again on the next request.

There are probably several solutions that would help (not taking into account how feasible they are):
* Do not pool arrays under 80 KB. This would increase pressure on the GC but would free memory not used.
* Use a single buffer (as the original version did) instead of two separate for read and write. This does not solve the issue but would require less memory.
* Let the dev provide their own implementation of the ArrayPool which could help them to optimize memory usage for their specific use case. This is probably not something that would be used by many (at least not in a correct way).

Unfortunately my time is very limited right now so I won't have any time the coming weeks to look into this issue more. Feel free to poke around and send a PR if you make any improvements. The code can be found in the AppendDataAsync method in the TusDiskStore class: https://github.com/tusdotnet/tusdotnet/blob/master/Source/tusdotnet/Stores/TusDiskStore.cs#L82

For now I think the only option is to restart (or if running on IIS, recycle) the app when traffic is low and also decrease the read/write buffer sizes to reduce overall memory usage. 

The good news is however that the app should not use more memory than the number of concurrent connections times the read and write buffer sizes at peak time and that any available buffer will be reused on the next request.

**Comment by SnGmng** [comment] 2020-08-10 12:26
This looks like the perfect use case of `System.IO.Pipelines` high performance io library  https://devblogs.microsoft.com/dotnet/system-io-pipelines-high-performance-io-in-net/

**Comment by smatsson** [comment] 2020-08-25 11:52
@SnGmng  While `System.IO.Pipelines` is a great tool for parsing data, it would not help us here. Both TusDiskStore and `System.IO.Pipelines` uses the same technique to allocate buffers (`ArrayPool<T>`). The difference is what we do with the data. Pipelines can allocate multiple smaller arrays and then return these arrays once they are no longer needed (basically after a call to `AdvanceTo`). TusDiskStore needs to allocate fewer but larger arrays to minimize disk IO and CPU usage. We do not need to parse the data but rather just keep it in memory over time.

Before 2.2 TusDiskStore used a single 50 KB buffer to do this. We filled it with as much data as we could get, up to 50 KB, and then wrote whatever we got to disk. This could sometimes be very heavy on the server in terms of disk IO and CPU so PR #57 tried to fix that by splitting the buffer in two. One for reading and a MemoryStream for buffering data before writing. The PR caused memory leaks as MemoryStream is backed by an array and once that array is almost full, a new array with double the size, would be allocated. This would then cause the new array to be 100 KB and thus being allocated in the large object heap (LOH). The LOH is not compressed the same way as the small object heap (a.k.a the regular heap) and thus a memory leak happened. 2.2 fixed that by using `ArrayPool<T>` to allocate buffers (the same way `System.IO.Pipelines` does). 

So the problem with `ArrayPool<T>` is that it does not deallocate things in the pool ever and this might cause issues in some scenarios and thus this memory leak happens.

So the next version of tusdotnet will optimize this behavior by doing the following:
* Use a single read/write buffer and use offsets instead of copies to read and write data. This would reduce overall memory usage.
* Move to using `ArrayPool<T>.Shared` instead of our own instance which would reduce overall memory usage as we can re-use arrays used by other parts of the app.
* Allow for pooling to be disabled so that the dev running the server can handle memory themselves, e.g. by calling [GC.Collect](https://docs.microsoft.com/en-us/dotnet/api/system.gc.collect?view=netcore-3.1) when necessary.
* Use array buckets instead of a single array when pooling is disabled and the write buffer is larger than LOH limit.

Other measurements might be implemented as well, such as using `Span<T>` for parsing e.g. `Upload-Metadata` and `Upload-Concat`. This would probably only have a slight effect on memory but every little helps.

**Comment by Bhaviya1** [comment] 2020-08-27 22:50
In order to solve the problem of LOH in Garbage Collector :-

1. Can we somehow split LOH into smaller objects ? If yes, will there be any performance degradation ? 
2. Can we try recycling the Pool periodically ?
3. Can we try compacting LOH by writing a logic ?
4. Can we try creating a Master-Slave for Pool where Master Pool will perform all writes and Once Master reaches threshold, it copies Large Objects in Slave Pool? Here the main advantage is, while copy from Master to Slave, all large objects will get copied next to each other, leaving enough free space at the end which were in Master Pool as fragmented (Free Space 1 + Free Space 2 + ..... + Free Space n). After that, we switch the roles of Master Pool and Slave Pool. Hence, Slave Pool now is the Master. It continues switching roles once it reaches threshold. In this way, we are not losing any data and there will not be performance degradation.

For Example :-

Master Pool :-
L1
L2
L3
L4
L5

Now, we remove L2 and L4 so Master Pool we now be :-
L1
Free Space
L3
Free Space
L5

Hence, perhaps there is not enough free space for new large objects. So, we copy to Slave Pool :-
L1
L3
L5
Free Space
Free Space

And this Slave Pool will be now Master Pool.

**Comment by smatsson** [comment] 2020-09-08 08:17
> Can we somehow split LOH into smaller objects ? If yes, will there be any performance degradation ?

Yes, this is mentioned as "array buckets" in my previous comment. The performance degradation depends on the size of the buffer. The larger the buffer the more overhead needed. The default buffer size does not have any degradation (except for GC pressure) and a 5 MB buffer uses roughly 2.5 times the memory as just placing it in the ArrayPool.

> Can we try recycling the Pool periodically ?

`ArrayPool<T>` does not have a function to recycle the pool. The problem isn't really the pool though. It's how to handle objects that are being removed from the pool (both SOH and LOH, but especially LOH). This was the original issue with how buffers are managed in the disk store.

> Can we try compacting LOH by writing a logic ?

Yes you can set `GCSettings.LargeObjectHeapCompactionMode` and then run a full `GC.Collect` to force* the GC to compress it. The problem is really that tusdotnet can't know when to run this as it has severe performance impacts when the GC is doing its thing.

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.gcsettings.largeobjectheapcompactionmode?view=netcore-3.1
https://docs.microsoft.com/en-us/dotnet/api/system.gc.collect?view=netcore-3.1

* Force and force. You can't really force the GC to do anything. You can give it a firm notice that it should do it now.

> Can we try creating a Master-Slave for Pool where Master Pool will perform all writes and Once Master reaches threshold, it copies Large Objects in Slave Pool? Here the main advantage is, while copy from Master to Slave, all large objects will get copied next to each other, leaving enough free space at the end which were in Master Pool as fragmented (Free Space 1 + Free Space 2 + ..... + Free Space n). After that, we switch the roles of Master Pool and Slave Pool. Hence, Slave Pool now is the Master. It continues switching roles once it reaches threshold. In this way, we are not losing any data and there will not be performance degradation.

I don't see how this would help at all? We do not allocate data inside the pool but on the heap. So each copy is basically allocating more memory and hoping that the source can be GCd.

**Comment by keithotto** [comment] 2020-09-24 19:04
Would this be an issue used on a web server? If incoming requests are separate processes that are then killed off after the request finishes, would that memory get freed up?

**Comment by smatsson** [comment] 2020-09-28 10:36
> Would this be an issue used on a web server? If incoming requests are separate processes that are then killed off after the request finishes, would that memory get freed up?

That's not how incoming requests are handled in .NET so yes, I would still be an issue on a web server. If each request _was_ handled as a different process then it would free up the memory when the request is over but we would have a whole lot of other perf issues instead. :)

**Comment by KhaledSMQ** [comment] 2020-10-30 14:29
I was reading this case and it came to my mind if we use [RecyclableMemoryStream ](https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream)library from Microsoft. What do you think?
Basically somehow the library trying to solve the problem by maintains two separate pools Small Pool and Large Pool. Starting from smaller pools and when the buffer grow it move it a the large pool.

**Comment by smatsson** [comment] 2020-11-02 10:36
@KhaledSMQ Thanks for the link, it might be a good solution. The progress on this issue has been slow, mainly because I haven't seen any of these issues on the servers where I run tusdotnet and no-one has provided a PR so how big of an issue can it be? ;)

**Comment by KhaledSMQ** [comment] 2020-11-06 11:44
@smatsson for me even I didn't notice this issue. all my uploads files are small size and did not have heavy load on the applications.
I will try this week to do some experiment at least to reproducer the problem.

**Comment by NateRadebaugh** [comment] 2021-02-19 14:54
My team is interested in a solution to this issue. I'm going to try a to refactor to use RecyclableMemoryStream in a fork and send a PR if it goes well.

**Comment by smatsson** [comment] 2021-02-23 12:00
@NateRadebaugh That would be very much appreciated. There are some ongoing work to try to fix this issue (e.g. PR 123) and some others that have not yet left my computer. I would love to benchmark the different ones to find a good default base line to use. In the future it will probably be needed to have some kind of interface for the buffering as there are so many variables to take into account (CPU, memory, upload speed, disk IO etc) that I don't think there is a silver bullet here.

`ClientDisconnectGuardedReadOnlyStream` is a stream that wraps the request stream and keeps track of the client to prevent an exception to be thrown when the client disconnects.

`ReadOnlyStreamWithPreReadByte` is used to determine if any data is available in the request (used for the creation-with-upload extension).

`ReadonlyStream` is the base class of each (not really sure why it's not marked as abstract).

You could probably just pass the stream returned by RecyclableMemoryStreamManager into `ClientDisconnectGuardedReadOnlyStream` and it would work out of the box (not including optimizations of course).

**Comment by smatsson** [comment] 2021-03-09 12:04
I finally got some spare time last week so I ran a bunch of tests and I think I have found the culprit here. It seems like the pool implementation used sometimes evicts pooled items which, as previously described, causes LOH allocations to not be re-used and thus causes memory fragmentation (a.k.a memory leaks). The memory fragmentation will be dealt with by .NET when it feels like it so the memory will be returned sometime, but it can still cause issues meanwhile. 

With ideas taken from RecyclableMemoryStream and System.IO.Pipelines (but optimized for our scenario) there is a branch that now uses nonconsecutive (a.k.a chunked) memory to store data instead of a single consecutive chunk which the current implementation uses. Each chunk is pooled in `ArrayPool<T>`. This means that there are no LOH allocations at all which helps with this entire issue. The downside is that the actual writing of the file to disk is slower as we need to write individual buffers instead of a single large one. For write buffers below the LOH limit (85 KB) there is no difference in using the new and the old code.

Please try it out and report back how it works for you: [87-memory-leak](https://github.com/tusdotnet/tusdotnet/tree/87-memory-leak)

There are some configuration options that can be tried out to optimize the code:
```csharp
return new DefaultTusConfiguration
            {
                UrlPath = "/files",
                Store = new TusDiskStore(@"C:\tusfiles\",
                                true,
                                new TusDiskBufferSize(5 * 1024 * 1024),
                                new tusdotnet.Stores.FileIdProviders.TusGuidProvider(),
                                new tusdotnet.Stores.BufferHandlers.NonConsecutiveMemoryBufferHandler(useAsynchronousFileIO: true, useAsynchronousCodeFlow: true)),
...

```

`useAsynchronousFileIO: true` tells the OS to open the underlying file in async mode (overlapped I/O on Windows and AIO on Posix).
`useAsynchronousCodeFlow: true` means to use the async version of the FileStream's Write method.

These two can be individually changed as they reference different things. It seems like setting both to false is slightly faster on localhost with a local SSD when using 200 simultaneous clients but it would probably not be the same for e.g. a NAS so please experiment with the two settings to find out which one works better in your case. 

It would help a lot if people in this thread experiencing memory leaks would try the branch above and report back:
* What kind of drive are you saving data to? Local SSD, local HDD, NAS?
* What buffer sizes are you using?
* Do you experience any difference when changing `useAsynchronousFileIO` and `useAsynchronousCodeFlow`

I have attached a zip to this post containing assemblies for .NET 4.5.2 and .NET Standard 1.3 together with the nuget package so either build the source from the branch or use one of the assemblies.
[87-memory-leak.zip](https://github.com/tusdotnet/tusdotnet/files/6108326/87-memory-leak.zip)

**Comment by jmoreno-safefleet** [comment] 2021-04-23 15:22
I took the branch, and I'm having problems with checksum matching when including the Upload-Checksum header.

**Comment by smatsson** [comment] 2021-04-26 08:59
@jmoreno-safefleet Do you have an example where it does not work? Just tried it it with multiple files in various sizes and they all worked. Make sure to use the correct encoding of your Upload-Checksum header. It seems that most tools on Windows will use the hex values of the hash while you want to just base64 encode the raw value as so (from Powershell):
```ps

$algorithm = [Security.Cryptography.HashAlgorithm]::Create("SHA1")
$fileBytes = [io.File]::ReadAllBytes("C:\location\to\some\file.bin")
[Convert]::ToBase64String($algorithm.ComputeHash($fileBytes))
```

Sample output would be something like `tlbOO9oQ3FprHxKX0A7GQGwNolI=` instead of `B656CE3BDA10DC5A6B1F1297D00EC6406C0DA252`

**Comment by jmoreno-safefleet** [comment] 2021-04-29 20:55
@smatsson We are using the TusDotNetClient library from https://github.com/jonstodle/TusDotNetClient .
We are attempting to send large files 500MB and above, using 60mb chunks.

The client library does convert the hash into base64.  Just to note, this TUS client did work with tusdotnet before the memory leak fix on this branch.

**Comment by smatsson** [comment] 2021-05-03 13:01
@jmoreno-safefleet Thanks for reporting. This seems... less than ideal :) I can recreate the issue with the linked client and the same chunk size. It does seem to work correctly for other chunk sizes so I'll have to do some investigation.

**Comment by smatsson** [comment] 2021-05-18 10:39
@jmoreno-safefleet This was a tricky one. I managed to get the error once and then, without changing anything, it just started working. 🤷‍♂️ Could you please post the tus configuration you are using?

**Comment by smatsson** [comment] 2021-09-22 09:52
Since there hasn't been much activity here lately I decided to go with the pipereader idea from https://github.com/tusdotnet/tusdotnet/issues/146

It's basically the same concept as the non-consecutive memory approach used here but uses the built in System.IO.Pipelines instead. You can check the performance comparison in the linked issue. TL;DR: It uses way less memory but the file is slower to write.

I'll close this issue once the next version is on nuget.

**Comment by smatsson** [comment] 2021-11-16 12:23
New version is out with support for System.IO.Pipelines. Feel free to test it out and open a new issue if the problem is not solved. 

https://www.nuget.org/packages/tusdotnet/2.5.0

**Closed by smatsson** 2021-11-16 12:23 UTC
